version: '3.5'

services:

  lowcode-engine-backend:
    container_name: lowcode-engine-backend-c
    image: registry.cn-shanghai.aliyuncs.com/leon-pu/lowcode-engine-backend:latest
    build: ./
    volumes:
      - "/var/lowcode-engine-backend/log:/var/lowcode-engine-backend/dist/log"
    ports:
      - "8802:3000"
    restart: always
    environment:
      DATABASE_HOST: eon-database
      DATABASE_PORT: 27017
      DATABASE_NAME: lowcode
      DATABASE_USER: leon
      DATABASE_PASSWORD: Leon.pu199139!
    networks:
      - devnet

networks:
  devnet:
    name: server-global-network
    external: true