version: '3.5'

services:

  custom-devkit-backend:
    container_name: custom-devkit-backend-c
    image: registry.cn-shanghai.aliyuncs.com/leon-pu/custom-devkit-backend:latest
    build: ./
    volumes:
      - "/var/custom-devkit-backend/log:/var/custom-devkit-backend/dist/log"
    ports:
      - "9901:3000"
    restart: always
    environment:
      DATABASE_HOST: eon-database
      DATABASE_PORT: 27017
      DATABASE_NAME: custom-devkit
      DATABASE_USER: leon
      DATABASE_PASSWORD: Leon.pu199139!
    networks:
      - devnet

networks:
  devnet:
    name: server-global-network
    external: true
